const step1 = {
    cephei: {
        title: 'An unfortunate surprise',
        content: '<img class="section__image--absolute" src="src/medias/asteroids.png" alt="Image of the asteroid field"><p class="section__text">On the road to Cephei, they detected a dysfunction on the monitors probably due to damage on the radars. They sent Mike Gramsy, general engineer and Mark Johnson, engineering technician to repare the radars. While they were outside the ship trying to repare the damage probably induced by crossing the wormhole months earlier, they detected a massive asteroids field moving towards their position at a speed of approximately 300 miles per hour. They couldn\'t give a burst of acceleration without ultimately killing the two astronauts. Collision was inevitable. When the asteroids finally reached their position a few minutes later, Mike made it back inside but Mark was to far away from the entrance, he got hit by an asteroid and died on the spot.</p><p class="section__text">The ship got hit by various asteroids, deviating its trajectory and critically damaging the west side of the ship were the fuel was stored. Due to the long distance between each asteroid, they miraculously made it out alive without destroying the ship for good, but the situation was critical and time was running out. Without having any time to cry their companion\'s death, they had to make a choice, ever go to Corona, which was now closer to their position or try to go to Cephei anyway. They had the best chance to make it to Corona alive before the ship finally breaks, but their best chance of surviving was on Cephei. They made the hard choice to go to...</p>',
        buttons: '<button class="button" id="button-chap5" data-target="cephei1"><img class="button__image" src="src/medias/cephei-min.png" alt="Image of Cephei"><p class="button__text">Cephei</p></button><button class="button" id="button-chap5" data-target="corona"><img class="button__image" src="src/medias/corona-min.png" alt="Image of Corona"><p class="button__text">Corona</p></button>',
    },
    corona: {
        title: 'Alien biodiversity',
        content: '<p class="section__text">When they reached Corona\'s atmosphere, it was so full of a yellow-brownish gas that they couldn\'t see anything. They held their breathes and continued navigating in the thick mist. Until they saw it, a land with mountains ten times higher than those on Earth, with dense vegetation and fluorescent colors everywhere. When they finally found a plan place to land the ship, they started doing some analysis. The air was unfortunately to charged up of ammonia for a human to survive more than 2 minutes without a suit, but the gravity was very enjoyable as it was 80% of the Earth\'s gravity. The planet was very hot in the day and very cold in the night.</p><p class="section__text">They collected data from the plants and it seemed like the plants were communicating through electrical impulses and that each plant was growing and dying independently while being also part of an entire network of cells linked together, by what appeared like some kind of nervous system. They assumed that the planet had some kind of central nervous system where all the data were coming and going, but after months of researches, they never found it. They had already been spending way more time than they ever expected and their resources were running out day by day. They had to make a decision: going to Cephei, continue their research and taking the risk to never come back to Earth or trying to go back to Earth immediately, knowing that they might never have this chance again. They decided to go to...</p>',
        buttons: '<button class="button" id="button-chap5" data-target="cephei2"><img class="button__image" src="src/medias/cephei-min.png" alt="Image of Cephei"><p class="button__text">Cephei</p></button><button class="button" id="button-chap5" data-target="earth"><img class="button__image" src="src/medias/earth-min.png" alt="Image of Earth"><p class="button__text">Earth</p></button>',
    },
    leonis: {
        title: 'A strange signal',
        content: '<p class="section__text">They had to go threw hibernation again, but this time was for a period of 3 years. This time could be damaging for their bodies, and even if they had a set of artificial intelligence monitoring every health parameter, it still could have been the last time they fall asleep. So they made the decision to wake up every year for a week in order to give their bodies a break. They prepared themselves, set up the spaceship to go to Leonis and fell asleep once again.</p><p class="section__text">A year later, when they all woke up from the first nap, co-pilot Lee Hathaway discovered that a signal had been emitted towards their position for four months.When they analysed the signal, they could not believe its complexity. They stayed up longer that intended to decode the message but realised that it would take years to understand. The one thing they were sure about, is that it had to be sent by someone or something. Some of the crew thought that it was nothing worth to pursue, that it was probably coming from an anomaly far away in this galaxy but the rest of the crew were convinced that it had to be sent for a reason and that the signal could definitely be a proof of an extraterrestrial life form. They decided to go to...</p>',
        buttons: '<button class="button" id="button-chap5" data-target="signal"><img class="button__image" src="src/medias/signal.png" alt="Image of the signal"><p class="button__text">Signal</p></button><button class="button" id="button-chap5" data-target="leonis"><img class="button__image" src="src/medias/leonis-min.png" alt="Image of Leonis"><p class="button__text">Leonis</p></button>',
    },
};

const step2 = {
    cephei1: {
        title: 'A new hope',
        content: '<p class="section__text">They chose to take the risk to go to Cephei anyway.When they reached Cephei atmosphere, the spaceship was in critical condition, forcing them to land in emergency. They crashed into the land without anyone hurt. After a couple of weeks of exploring this new world, it appeared to have a presence of oxygen in the air. Even tho they weren\'t able directly breath the air because of other chemicals in it, they could found a way to filter it. They also found a large presence of water, representing about 80% of Cephei\'s surface. But when it comes to vegetation and biodiversity, they hardly found anything.</p><p class="section__text">The food was their only big issue at the time even tho they could last a little bit more than a year with their supply. They decided to set up camp while trying to repare the spaceship, but they quickly understood that their best option would be to be rescued. So they created a high-frequency transmitter with what was left of the spaceship to send a signal directly at the wormhole, hopping that the Earth would get their story in time and finally, get rescued...</p>',
    },
    corona: {
        title: 'The loss of hope',
        content: '<p class="section__text">When they reached Corona\'s atmosphere, the spaceship was in critical condition, forcing them to land in emergency. The atmosphere was so full of a yellow-brownish gas that they couldn\'t see anything. They held their breaths and continued navigating in the mist. When they finally made it throw, they realised that the planet was full of rocks and mountains and that they had no choice but to crash the spaceship into one of them. They survived the crash but it caused irreversible damage to the ship and they lost more than half of their food and water supply.</p><p class="section__text">They all knew that they had close to no chance of making it out alive. They got out of the ship to explore their surrounding but found nothing but strange plants. There was no presence of food or water and the air wasn\'t breathable without their suit. They tried to create a high-frequency transmitter with what was left of the spaceship to send a signal directly at the wormhole, hopping that the Earth would get their message in time and finally get rescued, but as time was running out, they slowly started to accept their fate...</p>',
    },
    cephei2: {
        title: 'New discoveries',
        content: '<p class="section__text">They got through Cephei atmosphere without problems, landing successfully into the land. After a couple of weeks of exploring this new world, it appeared to have a presence of oxygen in the air. Even tho they weren\'t able to directly breath the air because of other chemicals in it, they could find a way to filter it. They also found a large presence of water, representing about 80% of Cephei\'s surface. But when it comes to vegetation and biodiversity, they hardly found anything. The food was the only big issue, but Cephei definitely could offer the possibility of setting up a colony in the future.</p><p class="section__text">Months past away when their resources were running out, so they decided to return home. They managed to make it back to Earth, bringing with them informations that allowed me to tell you that story today. But most importantly, they had set up a new era for humanity, an era of space explorations and colonisations, for many years to come...</p>',
    },
    earth: {
        title: 'New discovery',
        content: '<p class="section__text">They travelled back through the wormhole and made it back to Earth.When they arrived, the whole world was seeing them as heroes. The whole world knew who they were. The following months after their return, the best scientists and biologists were analysing the data they had found, trying to understand Corona\'s biodiversity. But after a while, people were convinced that the government was hiding informations from them, thinking that it had to be more that just the discovery of a new biodiversity and a few strange plants. But even tho they haven\'t found extraterrestrial life forms or even planet that could support life, now they knew that there was something more out there, waiting to be discovered...</p>',
    },
    signal: {
        title: 'Extra dimensionnal beings',
        content: '<p class="section__text">They followed the signal while they continued to analyse it, when something came up on their radars, it was a new planet. The closer they got to the planet, the higher the signal was. They assumed the signal was emitted from it. They did a series of observations on the planet and seemed impossible to land due to what seemed to be extremely intense waves of energy going out from it. They got as close as possible to it in order to get as much data as possible, until all the navigation commands and electronics started to dysfunction.</p><p class="section__text">All the speakers started to emit loud noises, and the ship began to spin and shake out of control. Out of the chaos appeared a form that looked like nothing the crew had ever seen before. The planet attraction force drastically changed sucking up the spaceship. The all crew thought it was the end, when everything suddenly stopped, the planet was gone and the strange being that appeared in front of their eyes, vanished. At this very moment, the crew knew that they had just witnessed the first contact with an extraterrestrial life form. They decided to return to Earth since the planet had just disappeared, but they had stored a signal that could very much be the way those beings tried to communicate with them...</p>',
    },
    leonis: {
        title: 'Nothing but silence',
        content: '<p class="section__text">When they tried to land on Leonis, the crew got trapped into a storm. The spaceship took irreparable damage lefting the crew stuck on the planet. They tried to survive for a couple of weeks trying to find a presence of water or anything that could help them stay alive, but they knew that their fate was sealed. So they managed to store their story into a capsule hopping that one day, the guys that will come after them will find it and learn about their journey. They died couple weeks after knowing that they were just the beginning of a new chapter for humanity...</p>',
    },
};
